---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/login":
    post:
      summary: create login
      responses:
        '200':
          description: successful
    get:
      summary: list logins
      responses:
        '200':
          description: successful
  "/login/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show login
      responses:
        '200':
          description: successful
    patch:
      summary: update login
      responses:
        '200':
          description: successful
    put:
      summary: update login
      responses:
        '200':
          description: successful
    delete:
      summary: delete login
      responses:
        '200':
          description: successful
  "/logout":
    get:
      summary: delete login
      responses:
        '200':
          description: successful
  "/user":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      responses:
        '200':
          description: successful
  "/user/new":
    get:
      summary: new user
      responses:
        '200':
          description: successful
  "/user/{id}/edit":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: edit user
      responses:
        '200':
          description: successful
  "/user/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      responses:
        '200':
          description: successful
    put:
      summary: update user
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
